### ISSUE TITLE
install

### ISSUE THREAD

**Issue by matsyoman** [xaphod/Bluepeer#2]
hello,

how do I install bluepeer and edit the pod file?

thanks!

Mats Dekker

**Comment by xaphod** [comment]
Hi Mats,
Is this the first cocoapod that you've ever installed? If so, please take a look here: https://guides.cocoapods.org/using/using-cocoapods.html

Basically you need to get cocoapods installed (ie. "sudo gem install cocoapods", using the password for your user), then open Terminal, go to the folder where your xcode project is, and type "pod init", then open the Podfile and put in the pods you want, then "pod install", then open the workspace instead of the project file in xcode.
